name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: make
    - name: Test
      shell: bash
      run: make test
    - name: Upload Antlr4BuildTasks artifacts
      uses: actions/upload-artifact@v2
      with:
         name: build-output
         path: /home/runner/work/Antlr4BuildTasks/bin/Debug/*.*nupkg
         retention-days: 3
  build-just-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: msys2/setup-msys2@v2
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: make
    - name: Test
      shell: bash
      run: make test
    - name: Upload Antlr4BuildTasks artifacts
      uses: actions/upload-artifact@v2
      with:
         name: build-output
         path: /home/runner/work/Antlr4BuildTasks/bin/Debug/*.*nupkg
         retention-days: 3

  build-alone:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: make
    - name: Test
      shell: bash
      run: make test-alone
  build-just-windows-alone:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: msys2/setup-msys2@v2
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: make
    - name: Test
      shell: bash
      run: make test-alone
