name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: make
    - name: Test
      shell: bash
      run: make test
    - name: Upload Antlr4BuildTasks artifacts
      uses: actions/upload-artifact@v2
      with:
         name: build-output
         path: /home/runner/work/Antlr4BuildTasks/bin/Debug/*.*nupkg
         retention-days: 3

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        java: [11]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: make
    - name: Test
      shell: bash
      run: make test
    - name: Upload Antlr4BuildTasks artifacts
      uses: actions/upload-artifact@v2
      with:
         name: build-output
         path: /home/runner/work/Antlr4BuildTasks/bin/Debug/*.*nupkg
         retention-days: 3

  build-ubuntu-multitarget:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latest
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: make
    - name: Test
      shell: bash
      run: make test-alone


  build-windows-multitarget:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: windows-latest
      fail-fast: false
    steps:
    - uses: msys2/setup-msys2@v2
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: make
    - name: Test
      shell: bash
      run: make test-alone
